title: Hassaan Malik
description: Aspiring computational social scientist
theme: jekyll-theme-minimal
logo: assets/img/circled photo.png
show_downloads: false
header_pages:
  - index.md
  - cv.md
  - projects.md
  - blog.md
  - learn.md
